Modify coreboot.u-root.systemboot/linux-4.19.6-linuxboot.config to enable EFI and EFI_STUB
Otherwise it will cause the following error when you make run
------------------------------------------------------------------------------
Error: Image at 00007B87000 start failed: 3
......
Error: Image at 00007BC4000 start failed: 8
......
LinuxBoot: signal ready to boot
LinuxBoot: Looking for bzimage
LinuxBoot: FFS buffer=00000000065EA018
LinuxBoot: FFS length=00481030
LinuxBoot: unable to load bzImage image
ASSERT [DxeCore] /home/uos/work/linuxboot/edk2/MdeModulePkg/Core/Dxe/DxeMain/DxeMain.c(607): ((BOOLEAN)(0==1))
!!!! X64 Exception Type - 03(#BP - Breakpoint)  CPU Apic ID - 00000000 !!!!
RIP  - 0000000007F33EC6, CS  - 0000000000000038, RFLAGS - 0000000000000202
RAX  - 0000000000000070, RCX - 0000000007F32D20, RDX - 00000000000003F8
RBX  - 0000000007F32CC0, RSP - 0000000007F32C80, RBP - 0000000007F52F70
RSI  - 0000000007F4F78E, RDI - 0000000007918C18
R8   - 0000000007F32D30, R9  - 0000000000000000, R10 - 0000000000000070
R11  - 0000000000000000, R12 - 0000000007F52F70, R13 - 0000000007A19018
R14  - 0000000007F524B8, R15 - 0000000000000001
DS   - 0000000000000030, ES  - 0000000000000030, FS  - 0000000000000030
GS   - 0000000000000030, SS  - 0000000000000030
CR0  - 0000000080010033, CR2 - 0000000000000000, CR3 - 0000000007C01000
CR4  - 0000000000000668, CR8 - 0000000000000000
DR0  - 0000000000000000, DR1 - 0000000000000000, DR2 - 0000000000000000
DR3  - 0000000000000000, DR6 - 00000000FFFF0FF0, DR7 - 0000000000000400
GDTR - 0000000007BEEA98 0000000000000047, LDTR - 0000000000000000
IDTR - 00000000078FE018 0000000000000FFF,   TR - 0000000000000000
-------------------------------------------------------------------------------

Signed-off-by: liuhuan <liuhuan@uniontech.com>